# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tag', widget: 'list', required: false}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: '_pages/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
    - label: Nav bar
      name: navbar
      file: '_data/nav.yml'
      fields:
        - label: 'Nav bar items'
          name: 'items'
          widget: 'list'
          fields:
          - { label: Title, name: title, widget: string}
          - { label: URL, name: url, widget: string}
    - label: Homepage
      name: homepage
      file: index.markdown
      fields:
        - { label: Image, name: image, widget: image }
        - { label: Intro, name: intro, widget: markdown }
        - { label: Bio, name: bio, widget: markdown }
        - { label: Post list header, name: list_title, widget: string, required: false }
    - label: 'Media'
      name: 'media'
      file: '_data/media.yml'
      fields:
        - label: 'Media description'
          name: 'description'
          widget: 'markdown'
        - label: 'Media items'
          name: 'items'
          widget: 'list'
          fields:
            - { label: Title, name: title, widget: string }
            - { label: Link, name: link, widget: string }
            - { label: Context, name: context, widget: string, required: false}
            - { label: Duration, name: duration, widget: string, required: false}
            - { label: Description, name: description, widget: markdown}
    - label: 'Press'
      name: 'press'
      file: '_data/press.yml'
      fields:
        - label: 'Press description'
          name: description
          widget: markdown
        - label: 'Press items'
          name: 'items'
          widget: 'list'
          fields:
            - { label: Headline, name: headline, widget: string }
            - { label: Outlet, name: outlet, widget: string }
            - { label: Link, name: link, widget: string }
            - { label: Date, name: date, widget: string }
            - { label: Quote, name: quote, widget: markdown}